### ISSUE TITLE
ERROR: Service 'meltingpot' failed to build

### ISSUE THREAD

**Issue by W0nIE** [cryptax/meltingpot#1]
`ADD failed: file not found in build context or excluded by .dockerignore: stat fs: file does not exist
`

**Comment by cryptax** [comment]
`./fs` is the directory of files you want to serve in the FTP server. This wasn't documented thanks for noting it + I add a test `./fs` directory so that the container builds correctly.

Note you'll have to tune `meltingpot.cfg`, `creds.cfg` and `./fs` to your own needs.

Fixed in commit 22b98549cb326a83992ae2aab5d8d62deaf2a3d1
